controller:
  admin:
    username: admin
    password: admin123

  serviceType: LoadBalancer

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - credentials-binding
    - blueocean
    - azure-credentials
    - azure-vm-agents
    - azure-container-agents

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  persistence:
    enabled: true
    size: 8Gi
    storageClass: default
    #storageClass: jenkins-sc

rbac:
  create: true
