apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-nginx
  template:
    metadata:
      labels:
        app: site-nginx
    spec:
      containers:
      - name: site-nginx
        image: higorluisbarbosa/site-treinamentos:v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: site-nginx-clusterip-service
            port: 
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: site-nginx-clusterip-service
  labels:
    app: site-nginx
spec:
  type: ClusterIP
  selector:
    app: site-nginx
  ports:
  - port: 80
    targetPort: 8000


