apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-homologacao
  namespace: homologacao
rules: 
  - apiGroups: 
      - "*"
    resources: 
      - services
      - pods
    verbs:
      - get
      - list
