apiVersion: v1
kind: Pod
metadata:
  name: mysql-config-pod
  labels:
    name: mysql-config-pod
spec:
  containers:
  - name: mysql-config-pod-container
    image: busybox
    command: ['sh', '-c', 'while true; do echo "Hostname: ${host}"; echo "Usuario: ${usuario}"; echo "Database: ${database}"; sleep 10; done ']
    envFrom:
    - configMapRef:
        name: mysql-config
    # ports:
    #   - containerPort: <Port>
