apiVersion: v1
kind: Pod
metadata:
  name: mysql-config-pod-volume
spec:
  containers:
  - name: mysql-config-pod-volume
    image: busybox
    command: ['sh', '-c', 'while true; do echo -e; cat /ect/data/host; echo -e; cat /ect/data/usuario; echo -e; cat /ect/data/database; sleep 10; done']
    volumeMounts:
    - name: mysql-config-pod-volume
      mountPath: /ect/data
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: mysql-config-pod-volume
    configMap:
      name: mysql-config
