apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-cliente-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-cronjob-container
            image: mysql:5.7
            command: ["sh", "-c", "mysql -h $HOSTNAME -u${USER} -p${PASSWORD} -e 'SHOW databases;'"]
            env:
            - name: HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: mysql-config
            - name: USER
              valueFrom:
                configMapKeyRef:
                  key: usuario
                  name: mysql-config
            - name: PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: senha
                  name: mysql-config
          restartPolicy: OnFailure
        