apiVersion: v1
kind: Pod
metadata:
  name: pod-files-dynamic
  labels:
    name: pod-files-dynamic
spec:
  containers:
  - name: pod-files-dynamic
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: "/mnt/azure"
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: pvc-files-dynamic
