apiVersion: v1
kind: Pod
metadata:
  name: pod-disk-static
  labels:
    name: pod-disk-static
spec:
  containers:
  - name: container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /mnt/azure
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: pvc-disk-static
