apiVersion: v1
kind: Pod
metadata:
  name: pod-multi
spec:
  containers:
  - name: container-1
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  
  - name: container-2
    image: alpine:latest
    command: ["watch", "wget", "-qO-", "localhost"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    # ports:
    #   - containerPort: 90
    
