apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-disk-static
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeName: pv-disk-static
  storageClassName: managed-csi
