apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-files-dynamic
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: sc-file-dynamic
