apiVersion: v1
kind: Pod
metadata:
  name: mysql-secret-volume-pod
spec:
  containers:
  - name: mysql-secret-volume-pod-container
    image: busybox
    command: ['sh', '-c', 'while true; do echo "Senha: $(cat /var/secret/senha)"; sleep 10; done']
    volumeMounts:
      - name: mysql-secret-volume-pod
        mountPath: /var/secret
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
