apiVersion: v1
kind: Pod
metadata:
  name: mysql-secret-pod
spec:
  containers:
  - name: mysql-secret-pod-containers
    image: busybox
    command: ['sh', '-c', 'while true; do echo "Senha: ${SENHA}"; sleep 10; done ']
    env:
      - name: SENHA
        valueFrom:
          secretKeyRef:
            name: mysql-senha
            key: senha
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
