apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-provider-class
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentity: ""
    keyvaultName: <nome_do_seu_cofre_key>
    cloudName: "AzurePublicCloud"
    objects: | 
      array:
        - | 
          objectName: mysql-senha
          objectType: secret
          objectVersion: ""
    tenanId: <seu_id_do_key_vault>